apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: kubernetes12cr.azurecr.io/kubernetes123repos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubernetes12cn

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kubernetes